services:
  influxdb:
    build: 
      context: .
      dockerfile: Dockerfile.influxdb
    container_name: RaspbianInfluxdb
    environment: 
      HOME: /home/user
    ports:
      8086:8086
    networks:
      - database
      - api
  datacollector:
    build: 
      context: .
      dockerfile: Dockerfile.datacollector
    networks:
      - database
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    networks:
      - database
      - api
    ports:
      3001:3001

networks:
  database:
    exteral: true