version: '3.7'
services:
  influxdb:
    build: 
      context: .
      dockerfile: Dockerfile.influxdb
    restart: on-failure
    environment: 
      HOME: /home/user
    ports:
      - 8086:8086
      - 3003:3003
      - 3004:8083
      - 8125:8125
    networks:
      - database
      - api
  datacollector:
    build: 
      context: .
      dockerfile: Dockerfile.datacollector
    restart: always
    privileged: true
    # network_mode used to be able to acces bluetooth devices in the container
    network_mode: "host"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=upgrade
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root
      - DOCKER_INFLUXDB_INIT_ORG=ruuvi
      - DOCKER_INFLUXDB_INIT_BUCKET=ruuvi
    depends_on:
      - "influxdb"
    # networks:
    #   - datacollector
    #   - database
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - "influxdb"
    volumes:
      - ./Api/src:/Api/src
      - ./Api/logs:/Api/logs
    networks:
      - database
      - api
    ports:
      - 3001:3001

networks:
  api:
    external: true
  database: